<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_ImportProject</name>
   <tag></tag>
   <elementGuidId>3faf09a9-4e01-418b-a488-86c8ae438b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-action-id=&quot;import-comm&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
