<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Components_Button</name>
   <tag></tag>
   <elementGuidId>b87eee2c-cdb2-4d2f-912f-d0d8ecd6c7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-original-title=&quot;Components&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
