<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_JobsActiviry</name>
   <tag></tag>
   <elementGuidId>58513618-e7f4-4bde-8364-ebb8b34b0267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;workspacegrid&quot;] div div:nth-child(2) tr:nth-child(2) td:nth-child(2) a:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1565256995315</value>
   </webElementProperties>
</WebElementEntity>
