<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Folder_exists_ERROR</name>
   <tag></tag>
   <elementGuidId>4aed2e00-20bf-420d-8a47-62d3ee8abcb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#errorMessageFolderExists</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
