<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Environment_list</name>
   <tag></tag>
   <elementGuidId>26c58aec-4e47-48d7-9161-6aa6dc88e1f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#environment-list</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
