<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sysinternals_Button</name>
   <tag></tag>
   <elementGuidId>72059183-4227-444b-b72e-3ac518d4816e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-original-title=&quot;Sysinternals&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
