<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Caption_TextArea</name>
   <tag></tag>
   <elementGuidId>a36a2a15-f41b-40e1-abba-42faf89fa311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;caption&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
