<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Preview_Button</name>
   <tag></tag>
   <elementGuidId>22d9a021-186f-4f63-bc95-eb5fb6522aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-action-id=&quot;formeditor-preview&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
