<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Remove_From_Favorites</name>
   <tag></tag>
   <elementGuidId>245254e1-c272-4f37-8f91-a575e4e7d269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-action-id=&quot;workspace-file-favorites-remove&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
