<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Demographics</name>
   <tag></tag>
   <elementGuidId>8c01776a-c82a-4f6e-a60b-170afa9dcdad</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demographics</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamic-properties&quot;)/form[@class=&quot;ecr-form form-horizontal form-run&quot;]/div[@class=&quot;form-pagination eos-tabs&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[@class=&quot;form-page-nav active&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
