<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_OnDemand</name>
   <tag></tag>
   <elementGuidId>96544fb8-3fd3-4525-b53f-36ed1f76fb6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-action-id=&quot;doceditor-save&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
