<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Page</name>
   <tag></tag>
   <elementGuidId>13c6af98-5e5a-4b40-a350-4919683a6a97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = '  Page' or . = '  Page')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#level-fields > div > div.formeditor-components > div > div > div.form_components > div:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_component</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Page</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;level-fields&quot;)/div[@class=&quot;formeditor-components-pane&quot;]/div[@class=&quot;formeditor-components&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ecr-components-section&quot;]/div[@class=&quot;form_components&quot;]/div[@class=&quot;form_component&quot;]</value>
   </webElementProperties>
</WebElementEntity>
